### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ebeyrent** [Oefenweb/php-statistics#6]
Hi there!

I noticed this code does not specify a license, and generally, this means that folks don't have permission to use, modify, or share this code.  This may have been an oversight on your part, or it may have been intentional.

Would you mind adding a license so that folks know whether or not they can use this library?

Thanks!

**Comment by tersmitten** [comment]
I'll add a license. It will be MIT by the way. Thanks for opening an issue.

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/php-statistics/releases/tag/v1.1.2

**Comment by ebeyrent** [comment]
Thank you!!
