### ISSUE TITLE
Problem of Statistics::variance calculation

### ISSUE THREAD

**Issue by peter279k** [Oefenweb/php-statistics#9]
As title, the case is as follows:

```php
use Oefenweb\Statistics\Statistics;

Statistics::variance([4]);
```

It should throw the following warning message:

```
PHP Warning:  Division by zero in /data/php-statistics/src/Statistics.php on line 143
```

I think it should check the length of `$count` before calculating the variance value.

BTW, on Python, it will throw following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/statistics.py", line 588, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points
```

I think we can consider scratching this approach :).

**Comment by tersmitten** [comment]
Can you propose a fix?

**Comment by peter279k** [comment]
@tersmitten, I create PR to resolve this issue.

Feel free to add some comments on this PR if having any recommendations :).

**Comment by tersmitten** [comment]
Merged
